name: Auto Release (workflow_run bridge)

on:
  workflow_run:
    workflows: ["Bump Version from Changelog"]
    types: [completed]

jobs:
  trigger-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PAT }}
      - name: Read version
        id: read_version
        run: echo "version=$(cat core/version_info.txt)" >> $GITHUB_OUTPUT
      - name: Ensure tag exists
        id: ensure_tag
        run: |
          ver="${{ steps.read_version.outputs.version }}"
          if git rev-parse -q --verify "refs/tags/v$ver" >/dev/null; then
            echo "found_tag=yes" >> $GITHUB_OUTPUT
            echo "Tag presence: yes"
          else
            echo "found_tag=no" >> $GITHUB_OUTPUT
            echo "Tag presence: no"
          fi
      - name: Dispatch release-auto (only if tag exists)
        if: steps.ensure_tag.outputs.found_tag == 'yes'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}
          event-type: version-bumped
          client-payload: '{"version": "${{ steps.read_version.outputs.version }}", "tag": "v${{ steps.read_version.outputs.version }}", "source": "workflow_run"}'
      - name: Skip (no tag)
        if: steps.ensure_tag.outputs.found_tag != 'yes'
        run: echo "No tag v${{ steps.read_version.outputs.version }} yet; skipping dispatch."